# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmeasure',
            name='high_message',
            field=models.CharField(default='High', max_length=255),
        ),
        migrations.AddField(
            model_name='experimentmeasure',
            name='low_message',
            field=models.CharField(default='Low', max_length=255),
        ),
        migrations.AddField(
            model_name='experimentmeasure',
            name='medium_message',
            field=models.CharField(default='Medium', max_length=255),
        ),
    ]
