# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:24
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('QualityManager', '0002_auto_20170328_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentmeasureresult',
            name='performed_at',
        ),
        migrations.AddField(
            model_name='experimentmeasureresult',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='experimentmeasureresult',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
