# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityManager', '0003_auto_20170328_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMeasureResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.FloatField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='experimentmeasureresult',
            name='raw_value',
            field=models.ManyToManyField(to='QualityManager.RawMeasureResult'),
        ),
    ]
