# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityManager', '0004_auto_20170330_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentmeasureresult',
            old_name='raw_value',
            new_name='raw_values',
        ),
    ]
