# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_key', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkbenchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=200)),
                ('can_run_experiments', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sshkeys',
            name='workbench_user',
            field=models.ManyToManyField(to='UserManager.WorkbenchUser'),
        ),
    ]
