# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('netid', models.CharField(max_length=200)),
                ('can_run_experiments', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
