# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_auto_20160510_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbenchuser',
            name='ssh_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
