# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmeasure',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
