# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments_manager', '0002_auto_20170426_0830'),
        ('quality_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentmeasureresult',
            name='experiment',
        ),
        migrations.AddField(
            model_name='experimentmeasureresult',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experiments_manager.ChosenExperimentSteps'),
            preserve_default=False,
        ),
    ]
