# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('feedback_like', models.TextField(null=True)),
                ('feedback_dislike', models.TextField(null=True)),
                ('other_comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_point', models.TextField()),
                ('end_point', models.TextField(null=True)),
                ('for_model', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='for_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Feedback.Task'),
        ),
    ]
