# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
        ('Feedback', '0002_task_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('left_feedback', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='dependent_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Feedback.Task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='for_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.Task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser'),
        ),
    ]
