# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 11, 6, 49, 577734, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
