# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubauth',
            name='workbench_user',
        ),
        migrations.RemoveField(
            model_name='gitrights',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='gitrights',
            name='user',
        ),
        migrations.RenameField(
            model_name='gitrepository',
            old_name='git_url',
            new_name='github_url',
        ),
        migrations.DeleteModel(
            name='GitHubAuth',
        ),
        migrations.DeleteModel(
            name='GitRights',
        ),
    ]
