# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20160621_1128'),
        ('GitManager', '0002_gitrepository_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, null=True)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('workbench_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser')),
            ],
        ),
    ]
