# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0003_remove_gitrepository_subrepos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitrepository',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='github_id',
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='has_issues',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='has_wiki',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='github_url',
            field=models.URLField(),
        ),
    ]
