# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0003_githubauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='github_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='hooks_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='git_url',
            field=models.CharField(max_length=100),
        ),
    ]
