# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20160621_1128'),
        ('GitManager', '0004_auto_20160628_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[(0, 'Read'), (1, 'Write'), (2, 'Read/Write')], default=0, max_length=2)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitManager.GitRepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser')),
            ],
        ),
    ]
