# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0005_gitrights'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='github_clone_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
