# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitManager', '0006_gitrepository_github_clone_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitrepository',
            name='github_clone_url',
        ),
    ]
