# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('internal_package', models.BooleanField(default=False)),
                ('project_page', models.URLField()),
                ('subscribed_users', models.ManyToManyField(to='user_manager.WorkbenchUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('resource', markdownx.models.MarkdownxField()),
                ('url', models.URLField(null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.WorkbenchUser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version_nr', models.CharField(max_length=50)),
                ('changelog', models.TextField()),
                ('url', models.URLField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.WorkbenchUser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
