# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('internal_package', models.BooleanField(default=False)),
                ('project_page', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subscribed_users', models.ManyToManyField(to='UserManager.WorkbenchUser')),
            ],
        ),
        migrations.CreateModel(
            name='PackageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', markdownx.models.MarkdownxField()),
                ('url', models.URLField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_nr', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField()),
                ('url', models.URLField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.Package')),
            ],
        ),
    ]
