# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('build_manager', '0001_initial'),
        ('requirements_manager', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpackage',
            name='requirements',
            field=models.ManyToManyField(to='requirements_manager.Requirement'),
        ),
        migrations.AddField(
            model_name='internalpackage',
            name='travis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='build_manager.TravisInstance'),
        ),
    ]
