# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20170502_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpackage',
            name='git_repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='git_manager.GitRepository'),
        ),
    ]
