# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20170421_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='pre_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
