# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0003_auto_20170313_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='title',
            new_name='package_name',
        ),
    ]
