# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170421_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='PackageLanguage',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
    ]
