# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170510_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageresource',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packageresource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
