# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
        ('Marketplace', '0005_auto_20170314_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='subscriped_users',
            field=models.ManyToManyField(to='UserManager.WorkbenchUser'),
        ),
    ]
