# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20170510_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpackage',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookiecutter_manager.CookieCutterTemplate'),
            preserve_default=False,
        ),
    ]
