# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0006_package_subscriped_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='subscriped_users',
            new_name='subscribed_users',
        ),
    ]
