# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20170521_1335'),
        ('marketplace', '0006_internalpackage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('for_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Package')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.WorkbenchUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
