# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0007_auto_20170314_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
