# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_packagerecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagerecommendation',
            name='for_package',
        ),
        migrations.RemoveField(
            model_name='packagerecommendation',
            name='liked_by',
        ),
        migrations.DeleteModel(
            name='PackageRecommendation',
        ),
    ]
