# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20170521_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recommended',
            field=models.IntegerField(default=0),
        ),
    ]
