# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_packageresource_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageresource',
            name='resource',
            field=models.TextField(),
        ),
    ]
