# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20170526_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpackage',
            name='project_page',
            field=models.URLField(help_text='URL to the project page of the package, for example to the PyPi location'),
        ),
        migrations.AlterField(
            model_name='packageresource',
            name='resource',
            field=models.TextField(help_text='Markdown allowed'),
        ),
        migrations.AlterField(
            model_name='packageresource',
            name='url',
            field=models.URLField(blank=True, help_text='URL to resource (optional)', null=True),
        ),
    ]
