# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('last_ping', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('AV', 'Beschikbaar'), ('BU', 'Bezig'), ('UN', 'Onbekend'), ('DO', 'Offline'), ('ER', 'Error')], default='UN', max_length=20)),
            ],
        ),
    ]
