# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('NO', 'Not available'), ('BU', 'Busy'), ('UN', 'Unknown'), ('DO', 'Offline'), ('ER', 'Error')], default='UN', max_length=20),
        ),
    ]
