# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('last_ping', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NO', 'Not available'), ('BU', 'Busy'), ('UN', 'Unknown'), ('DO', 'Offline'), ('ER', 'Error')], default='UN', max_length=2)),
                ('communication_key', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
