# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('experiment_git_url', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('RU', 'Running'), ('PE', 'Pending'), ('SU', 'Success'), ('FA', 'Failed'), ('CA', 'Cancelled')], default='PE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
