# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_submittedexperiments_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedexperiments',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submittedexperiments',
            name='repo_name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
