# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_auto_20160926_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedexperiments',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('RU', 'Running'), ('SU', 'Success'), ('ER', 'Error'), ('CA', 'Cancelled')], default='CR', max_length=2),
        ),
    ]
