# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0004_auto_20160926_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinformation',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
