# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('C', 'Cancelled'), ('F', 'Failed'), ('S', 'Success')], max_length=1, null=True),
        ),
    ]
