# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0002_auto_20170330_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Cancelled'), ('S', 'Success')], max_length=1, null=True),
        ),
    ]
