# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0005_auto_20170405_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('F', 'Failed'), ('S', 'Success'), ('C', 'Cancelled')], max_length=1, null=True),
        ),
    ]
