# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCutterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('meant_for', models.CharField(choices=[('e', 'Experiment'), ('p', 'Package')], default='e', max_length=10)),
            ],
        ),
    ]
