# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170427_1415'),
        ('cookiecutter_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiecuttertemplate',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Language'),
            preserve_default=False,
        ),
    ]
