# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments_manager', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('cookiecutter_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiecuttertemplate',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Language'),
        ),
        migrations.AddField(
            model_name='cookiecutterlocationtostepmapping',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments_manager.ExperimentStep'),
        ),
    ]
