# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments_manager', '0005_chosenexperimentsteps_location'),
        ('cookiecutter_manager', '0002_cookiecuttertemplate_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCutterLocationToStepMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('cookiecutter', models.ManyToManyField(to='cookiecutter_manager.CookieCutterTemplate')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments_manager.ExperimentStep')),
            ],
        ),
    ]
