# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiecutter_manager', '0003_cookiecutterlocationtostepmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiecutterlocationtostepmapping',
            name='cookiecutter',
        ),
        migrations.AddField(
            model_name='cookiecuttertemplate',
            name='folder_file_locations',
            field=models.ManyToManyField(to='cookiecutter_manager.CookieCutterLocationToStepMapping'),
        ),
    ]
