# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PylintResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pylint_type', models.CharField(max_length=1)),
                ('message', models.CharField(max_length=100)),
                ('line_nr', models.IntegerField()),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PylintScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('last_scan', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PylintScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('nr_of_errors', models.IntegerField(default=0)),
                ('nr_of_warnings', models.IntegerField(default=0)),
                ('nr_of_other_issues', models.IntegerField(default=0)),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylint_manager.PylintScan')),
            ],
        ),
        migrations.AddField(
            model_name='pylintresult',
            name='for_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylint_manager.PylintScanResult'),
        ),
    ]
