# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0001_initial'),
        ('RequirementsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentrequirement',
            unique_together=set([('package_name', 'experiment')]),
        ),
    ]
