# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='format',
            field=models.CharField(blank=True, help_text='Define a format (only for Date/Time/DateTime)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='max_length',
            field=models.IntegerField(null=True, verbose_name='maxLength'),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='maximum',
            field=models.CharField(blank=True, help_text='(optional) Define a maximum value', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='min_length',
            field=models.IntegerField(null=True, verbose_name='minLength'),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='minimum',
            field=models.CharField(blank=True, help_text='(optional) Define a minimum value (only for Number/Date/Time/DateTime) ', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='required',
            field=models.BooleanField(default=False, help_text='Field is required'),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='unique',
            field=models.BooleanField(default=False, help_text='Values in this row have to be unique'),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('year', 'Year'), ('yearmonth', 'Year Month'), ('boolean', 'Boolean'), ('object', 'Object'), ('geopoint', 'GeoPoint'), ('array', 'Array'), ('duration', 'Duration'), ('any', 'Any')], max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the contents of the field'),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='name',
            field=models.CharField(help_text='Name of row', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='primary_key',
            field=models.BooleanField(default=False, help_text='Field is a primary key'),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='title',
            field=models.CharField(blank=True, help_text='Title of field', max_length=100),
        ),
    ]
