# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema_manager', '0002_auto_20170503_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschemafield',
            name='constraints',
        ),
        migrations.AddField(
            model_name='dataschemafield',
            name='constraints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataschema_manager.DataSchemaConstraints'),
        ),
    ]
