# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema_manager', '0003_auto_20170503_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='format',
            field=models.CharField(help_text='Define a format (only for Date/Time/DateTime)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='maximum',
            field=models.CharField(help_text='(optional) Define a maximum value', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='minimum',
            field=models.CharField(help_text='(optional) Define a minimum value (only for Number/Date/Time/DateTime) ', max_length=100, null=True),
        ),
    ]
