# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema_manager', '0004_auto_20170503_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemafield',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('year', 'Year'), ('yearmonth', 'Year Month'), ('boolean', 'Boolean'), ('object', 'Object'), ('geopoint', 'GeoPoint'), ('array', 'Array'), ('duration', 'Duration'), ('any', 'Any')], max_length=100, verbose_name='type'),
        ),
    ]
