# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema_manager', '0005_auto_20170503_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='format',
            field=models.CharField(blank=True, help_text='Define a format (only for Date/Time/DateTime)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='max_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='maxLength'),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='maximum',
            field=models.CharField(blank=True, help_text='(optional) Define a maximum value', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='min_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='minLength'),
        ),
        migrations.AlterField(
            model_name='dataschemaconstraints',
            name='minimum',
            field=models.CharField(blank=True, help_text='(optional) Define a minimum value (only for Number/Date/Time/DateTime) ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataschemafield',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('year', 'Year'), ('yearmonth', 'Year Month'), ('boolean', 'Boolean'), ('object', 'Object'), ('geopoint', 'GeoPoint'), ('array', 'Array'), ('duration', 'Duration'), ('any', 'Any')], max_length=100, verbose_name='type'),
        ),
    ]
