# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravisCiConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_version', models.CharField(default='3.6', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravisInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_build_status', models.CharField(choices=[('S', 'Success'), ('C', 'Cancelled'), ('F', 'Failed')], max_length=1, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='build_manager.TravisCiConfig')),
            ],
        ),
    ]
