# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Cancelled'), ('S', 'Success')], max_length=1, null=True),
        ),
    ]
