# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_manager', '0002_auto_20170521_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travisinstance',
            name='last_build_status',
        ),
    ]
