# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_manager', '0002_auto_20170411_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('C', 'Cancelled'), ('S', 'Success'), ('F', 'Failed')], max_length=1, null=True),
        ),
    ]
