# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_manager', '0005_auto_20170427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Cancelled'), ('S', 'Success')], max_length=1, null=True),
        ),
    ]
