# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_manager', '0010_auto_20170503_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travisinstance',
            name='last_build_status',
            field=models.CharField(choices=[('S', 'Success'), ('C', 'Cancelled'), ('F', 'Failed')], max_length=1, null=True),
        ),
    ]
