# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerManager', '0001_initial'),
        ('ExperimentsManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentWorkerRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('RU', 'Running'), ('SU', 'Success'), ('ER', 'Error'), ('CA', 'Cancelled')], default='CR', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField(blank=True)),
                ('selected_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkerManager.Worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
