# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0002_experimentworkerrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenExperimentSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_nr', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExperimentsManager.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('default_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='chosenexperimentsteps',
            name='experiment_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExperimentsManager.ExperimentStep'),
        ),
    ]
