# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0002_auto_20160510_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='git_repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GitManager.GitRepository'),
        ),
        migrations.AlterField(
            model_name='script',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
