# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0002_auto_20170328_1429'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chosenexperimentsteps',
            managers=[
            ],
        ),
    ]
