# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0003_auto_20170315_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosenexperimentsteps',
            old_name='experiment_step',
            new_name='step',
        ),
        migrations.AddField(
            model_name='chosenexperimentsteps',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
