# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20160621_1128'),
        ('WorkerManager', '0003_worker_communication_key'),
        ('ExperimentsManager', '0003_auto_20160609_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('SU', 'Submitted'), ('SA', 'Started'), ('SO', 'Stopped'), ('ER', 'Error')], default='CR', max_length=2)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExperimentsManager.Experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.WorkbenchUser')),
                ('selected_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkerManager.Worker')),
            ],
        ),
    ]
