# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0004_experimentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentrun',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
