# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExperimentsManager', '0005_experimentrun_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentrun',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('RU', 'Running'), ('SU', 'Success'), ('ER', 'Error'), ('CA', 'Cancelled')], default='CR', max_length=2),
        ),
    ]
